---

- name: install nwipe
  apt:
          name: nwipe
          state: present

- name: install mutt
  apt:
          name: mutt
          state: present


- name: copy nukestation.sh
  copy:
          src: nukestation.sh
          dest: /usr/local/sbin/nukestation.sh
          mode: 0700
          owner: root
          group: root

- name: create logdir
  file:
          path: /var/log/nukestation
          state: directory
          mode: 0755
          owner: root
          group: root

- name: create config-dir
  file:
          path: /etc/nukestation
          state: directory
          mode: 0750
          owner: root
          group: root

- name: create pre-config-dir
  file:
          path: /etc/nukestation/pre.d
          state: directory
          mode: 0750
          owner: root
          group: root

- name: create post-config-dir
  file:
          path: /etc/nukestation/post.d
          state: directory
          mode: 0750
          owner: root
          group: root

- name: copy systemd-service
  copy:
          src: nukestation.service
          dest: /etc/systemd/system/nukestation@.service
          owner: root
          group: root
  notify: udevreload


- name: copy udev-rule
  copy:
          src: usb-wipe.rules
          dest: /etc/udev/rules.d/80-usb-wipe.rules
          owner: root
          group: root
  notify: udevreload

